### ISSUE TITLE
Parenthesized CG categories being confused with Penn Treebank node brackets

### ISSUE THREAD

**Issue by aslemen** [masashi-y/depccg#12]
## Issue description
DepCCG appears to bracket complex CG categories with parentheses (e.g. `(S[smc]\PP[s])\PP[o1]`) in all the provided output formats.
These parentheses, however, conflict with those dedicated to other roles such as those in the Penn Treebank Format, which indicate node boundaries, confusing other programs. 

## Steps to reproduce the issue
```sh
echo "太郎は花子に怒られた" | depccg_ja --format ptb
```

## What's the actual result?
```
(ROOT (S[mod=nm,form=base,fin=f] (NP[case=ga,mod=nm,fin=f] (NP[case=nc,mod=nm,fin=f] 太郎) (NP[case=ga,mod=nm,fin=f]\NP[case=nc,mod=nm,fin=f] が)) (S[mod=nm,form=base,fin=f]\NP[case=ga,mod=nm,fin=f] (NP[case=ni,mod=nm,fin=f] (NP[case=nc,mod=nm,fin=f] 花子) (NP[case=ni,mod=nm,fin=f]\NP[case=nc,mod=nm,fin=f] に)) ((S[mod=nm,form=base,fin=f]\NP[case=ga,mod=nm,fin=f])\NP[case=ni,mod=nm,fin=f] ((S[mod=nm,form=cont,fin=f]\NP[case=ga,mod=nm,fin=f])\NP[case=ni,mod=nm,fin=f] ((S[mod=nm,form=r,fin=f]\NP[case=ga,mod=nm,fin=f])\NP[case=ni,mod=nm,fin=f] 怒ら) (S[mod=nm,form=cont,fin=f]\S[mod=nm,form=r,fin=f] れ)) (S[mod=nm,form=base,fin=f]\S[mod=nm,form=cont,fin=f] た)))))
```

## What's the expected result?
The label of the following tree fragment should use any brackets other than `(` and `)`.
```
((S[mod=nm,form=r,fin=f]\NP[case=ga,mod=nm,fin=f])\NP[case=ni,mod=nm,fin=f] 怒ら) 
```
For example, it should be anything like
```
(<S[mod=nm,form=r,fin=f]\NP[case=ga,mod=nm,fin=f]>\NP[case=ni,mod=nm,fin=f] 怒ら) 
```

**Comment by masashi-y** [comment]
Hi, thank you for pointing out a problem, but I don't think I will change my code accordingly, due to the following reasons:
- Though the current format may be confusing for existing programs (e.g. NLTK), at least a user can write a parser on his own that does not heavily rely on the brackets to decide tree structure.
- The ptb format is not implemented so that it is used to work with other programs, rather it is there because it is much easier to read than the default auto format.
- The suggested solution using the angle brackets is also confusing for existing programs that parse _categories_ into some tree-like structure.

I suggest you to use other formats (json or XML for example) and convert the output to the one in your favorite format.
If you are working with depccg in the [programatic usage](https://github.com/masashi-y/depccg#programatic-usage), you can write a recursive function to convert the parsed output `Tree` objects to ptb-style string and use regular expressions to modify the bracketing in the CCG categories:

```python
    def ptb(tree):
        def rec(node):
            if node.is_leaf:
                cat = str(node.cat)  # use regex here
                word = node.word
                return f'({cat} {word})'
            else:
                cat = str(node.cat)  # use regex here
                children = ' '.join(rec(child) for child in node.children)
                return f'({cat} {children})'
        return f'(ROOT {rec(tree)})'

```
